# Generated by Django 4.2.10 on 2024-02-21 10:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myProject',
            fields=[
                ('geomp', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('polygon_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
            ],
        ),
    ]
